export interface BrowsingEvent {
  id: string;
  title: string;
  url: string;
  parentId: string | null;
  timeSpentSeconds: number;
  timestamp: string;
  // Nuances
  navigationType: 'clicked' | 'searched' | 'typed' | 'redirect' | 'back';
  discoverySource: 'google' | 'reddit' | 'hackernews' | 'direct' | 'documentation' | 'distraction';
  scrollDepth: number; // 0-100
  interactionCount: number;
  isInsight: boolean; // "Aha!" moment
}

export const mockBrowsingEvents: BrowsingEvent[] = [
  {
    id: "root-1",
    title: "Google: how to build a SaaS",
    url: "https://www.google.com/search?q=how+to+build+a+SaaS",
    parentId: null,
    timeSpentSeconds: 45,
    timestamp: "2026-05-03T10:00:00Z",
    navigationType: 'typed',
    discoverySource: 'google',
    scrollDepth: 30,
    interactionCount: 5,
    isInsight: false,
  },
  {
    id: "node-2",
    title: "The Ultimate Guide to Building a SaaS",
    url: "https://blog.hubspot.com/service/how-to-build-a-saas",
    parentId: "root-1",
    timeSpentSeconds: 650,
    timestamp: "2026-05-03T10:01:00Z",
    navigationType: 'searched',
    discoverySource: 'google',
    scrollDepth: 85,
    interactionCount: 24,
    isInsight: true, // Insight node
  },
  {
    id: "node-3",
    title: "Choosing a Tech Stack for SaaS",
    url: "https://stackshare.io/saas-tech-stack",
    parentId: "node-2",
    timeSpentSeconds: 120,
    timestamp: "2026-05-03T10:12:00Z",
    navigationType: 'clicked',
    discoverySource: 'direct',
    scrollDepth: 40,
    interactionCount: 12,
    isInsight: false,
  },
  {
    id: "node-4",
    title: "Next.js vs Remix for SaaS",
    url: "https://vercel.com/blog/nextjs-vs-remix",
    parentId: "node-3",
    timeSpentSeconds: 450,
    timestamp: "2026-05-03T10:15:00Z",
    navigationType: 'clicked',
    discoverySource: 'direct',
    scrollDepth: 95,
    interactionCount: 18,
    isInsight: true,
  },
  {
    id: "node-5",
    title: "Reddit: Best SaaS stacks in 2026",
    url: "https://www.reddit.com/r/saas/best_stacks",
    parentId: "node-3",
    timeSpentSeconds: 300,
    timestamp: "2026-05-03T10:25:00Z",
    navigationType: 'searched',
    discoverySource: 'reddit',
    scrollDepth: 100,
    interactionCount: 45,
    isInsight: false,
  },
  {
    id: "node-6",
    title: "Pricing your SaaS: Best Practices",
    url: "https://www.priceintelligently.com/blog/saas-pricing-models",
    parentId: "node-2",
    timeSpentSeconds: 800,
    timestamp: "2026-05-03T10:35:00Z",
    navigationType: 'clicked',
    discoverySource: 'direct',
    scrollDepth: 90,
    interactionCount: 30,
    isInsight: true,
  },
  {
    id: "node-7",
    title: "Cat Videos - YouTube",
    url: "https://www.youtube.com/watch?v=cat-distraction",
    parentId: "node-5",
    timeSpentSeconds: 5,
    timestamp: "2026-05-03T10:38:00Z",
    navigationType: 'clicked',
    discoverySource: 'distraction',
    scrollDepth: 5,
    interactionCount: 1,
    isInsight: false,
  },
  {
    id: "node-8",
    title: "Stripe Docs: Subscriptions",
    url: "https://stripe.com/docs/billing",
    parentId: "node-6",
    timeSpentSeconds: 1200,
    timestamp: "2026-05-03T10:45:00Z",
    navigationType: 'clicked',
    discoverySource: 'documentation',
    scrollDepth: 98,
    interactionCount: 60,
    isInsight: true,
  },
  {
    id: "node-9",
    title: "HackerNews: SaaS is dead?",
    url: "https://news.ycombinator.com/item?id=saas-dead",
    parentId: "root-1",
    timeSpentSeconds: 200,
    timestamp: "2026-05-03T10:10:00Z",
    navigationType: 'searched',
    discoverySource: 'hackernews',
    scrollDepth: 50,
    interactionCount: 8,
    isInsight: false,
  },
  {
    id: "node-10",
    title: "AWS Free Tier Details",
    url: "https://aws.amazon.com/free",
    parentId: "node-3",
    timeSpentSeconds: 8,
    timestamp: "2026-05-03T10:18:00Z",
    navigationType: 'clicked',
    discoverySource: 'direct',
    scrollDepth: 10,
    interactionCount: 2,
    isInsight: false,
  },
  {
    id: "node-11",
    title: "Back to: The Ultimate Guide",
    url: "https://blog.hubspot.com/service/how-to-build-a-saas",
    parentId: "node-10",
    timeSpentSeconds: 100,
    timestamp: "2026-05-03T10:19:00Z",
    navigationType: 'back', // NUANCE: User went back
    discoverySource: 'direct',
    scrollDepth: 85,
    interactionCount: 5,
    isInsight: false,
  },
  {
    id: "node-12",
    title: "PostgreSQL Perf Tips",
    url: "https://postgrescheatsheet.com",
    parentId: "node-8",
    timeSpentSeconds: 700,
    timestamp: "2026-05-03T11:00:00Z",
    navigationType: 'clicked',
    discoverySource: 'documentation',
    scrollDepth: 92,
    interactionCount: 20,
    isInsight: true,
  },
  {
    id: "node-13",
    title: "Product Hunt: New SaaS",
    url: "https://www.producthunt.com",
    parentId: "node-5",
    timeSpentSeconds: 150,
    timestamp: "2026-05-03T10:30:00Z",
    navigationType: 'clicked',
    discoverySource: 'direct',
    scrollDepth: 30,
    interactionCount: 15,
    isInsight: false,
  },
  {
    id: "node-14",
    title: "Tailwind CSS Starters",
    url: "https://github.com/saas-starters",
    parentId: "node-4",
    timeSpentSeconds: 300,
    timestamp: "2026-05-03T10:20:00Z",
    navigationType: 'clicked',
    discoverySource: 'direct',
    scrollDepth: 60,
    interactionCount: 10,
    isInsight: false,
  },
  {
    id: "node-15",
    title: "Weather in Bali",
    url: "https://www.google.com/search?q=weather+bali",
    parentId: "node-13",
    timeSpentSeconds: 3,
    timestamp: "2026-05-03T10:35:00Z",
    navigationType: 'searched',
    discoverySource: 'google',
    scrollDepth: 10,
    interactionCount: 1,
    isInsight: false,
  },
];
